// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // One folder per panel (getting-started, super-admin, school-admin, ...); pages are ordered by sidebar_position.
  tutorialsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
